c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/inifilelib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/matplotlib-3d.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/dblib/sqlitelib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/digikamlib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/stringslib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/dblib/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/digikam_models.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/dblib/dblib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/crustacean.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/heatmap.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/plots.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/mediandistance.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/focalpermute.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/stackedbargraph.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/test.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/statslib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/heatmap_conditionals.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/seabornlib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/test.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/focalpermute/quantile_regression_demo.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/shell_lib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/matplotlib-2d.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/excellib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/arcgis/test.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/plotlib/matplotliblib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/arcgis/rasterlib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/arcgis/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/numericslib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/permanal/main.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/permanal/test.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/example_scripts/physutil.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/skeleton/setup.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/skeleton/tests/NAME_tests.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/skeleton/tests/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/skeleton/NAME/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/eye_sunglasses.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/mouse_webcam.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/augmented_reality.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/augmented_reality_circular_motion.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/augmented_reality_dancing.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/augmented_reality_linear_motion.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/augmented_reality_variable_height.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 12/pose_estimation.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 11/find_fund_matrix.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 11/stereo_match.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/classify_data.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/Old/classify_data.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/create_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/Old/create_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/dense_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/Old/dense_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/training.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 10/Old/training.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/optical_flow.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/optical_flow.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/Old/optical_flow.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/frame_diff.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/frame_diff.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/Old/frame_diff.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/background_subtraction.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/background_subtraction.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/Old/background_subtraction.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/camshift.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/camshift.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/Old/camshift.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/crustacean/colorspaces.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/colorspaces.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 9/Old/colorspaces.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/contour_approx.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/convexity_defects_ver1.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/convexity_defects_ver2.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/grabcut.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/shape_censor.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 8/shape_matcher.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 7/object_removal.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 7/seam_carver_compress.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 7/seam_carver_expand.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 6/feature_matching.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 6/Old/feature_matching.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 6/pano_stitch.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 6/Old/pano_stitch.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/brief_with_fast.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/brief_with_fast.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/brief_with_star.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/brief_with_star.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/fast.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/fast.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/good_features_to_track.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/good_features_to_track.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/harris_corners.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/harris_corners.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/orb.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/orb.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/sift_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/sift_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/Old/surf_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 5/surf_features.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/ear_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/ear_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/eye_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/eye_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/eye_sunglasses.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/face_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/face_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/face_hannibal.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/face_hannibal.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/face_skull.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/face_skull.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/mouth_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/mouth_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/mouth_moustache.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/mouth_moustache.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/nose_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/nose_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/pupil_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 4/Old/pupil_detector.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/Old/convolution.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/Old/edge_detection.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/Old/histogram.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/Old/image_filters.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/Old/vignette.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/affine.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/color_spaces.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/geometric_transformations.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/projective.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/read_display_save.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/Old/warping.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/bilateral_filter.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/cartoonize.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/keyboard.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/median_filter.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/mouse_simple.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/mouse_webcam.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/Old/webcam.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/convolution.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/edge_detection.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/histogram.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/image_filters.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 2/vignette.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/affine.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/color_spaces.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/geometric_transformations.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/projective.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/read_display_save.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 1/warping.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/bilateral_filter.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/cartoonize.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/keyboard.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/median_filter.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/mouse_simple.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/OpenCVbyExample/Chapter 3/webcam.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/pyqtlib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/test.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/iolib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/lenscorrection.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/configlib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/imagedb/imagedb.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/arraylib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/imagedb/model.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/dblib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/baselib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/funclib/pandaslib.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/imagedb/__init__.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/common.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/opencvlib/lenscorrectiondb.py"
c:/python352/Scripts/futurize -w -1 "C:/Development/python/permanal/corr_tests.py"
pause