'''ifca stuff'''
from mmo import clean

#from  ifca_area_wgs84
VALID_IFCAS = clean(['Cornwall', 'Devon and Severn', 'Eastern', 'Isles of Scilly', 'Kent and Essex', 'North East', 'North West', 'Northumberland', 'Southern', 'Sussex'])

#from counties_wgs84
VALID_COUNTIES = clean(['Barking and Dagenham', 'Bath and North East Somerset', 'Bedfordshire', 'Berkshire', 'Bexley', 'Blackburn with Darwen', 'Bournemouth', 'Brent', 'Brighton and Hove', 'Bristol', 'Bromley', 'Buckinghamshire', 'Cambridgeshire', 'Camden', 'Cheshire', 'Cornwall', 'Croydon', 'Cumbria', 'Darlington', 'Derby', 'Derbyshire', 'Devon', 'Dorset', 'Durham', 'Ealing', 'East Riding of Yorkshire', 'East Sussex', 'Enfield', 'Essex', 'Gloucestershire', 'Greenwich', 'Hackney', 'Halton', 'Hammersmith and Fulham', 'Hampshire', 'Haringey', 'Harrow', 'Hartlepool', 'Havering', 'Herefordshire', 'Hertfordshire', 'Hillingdon', 'Hounslow', 'Isle of Wight', 'Islington', 'Kensington and Chelsea', 'Kent', 'Kingston upon Hull', 'Kingston upon Thames', 'Lambeth', 'Lancashire', 'Leicester', 'Leicestershire', 'Lewisham', 'Lincolnshire', 'London', 'Luton', 'Manchester', 'Medway', 'Merseyside', 'Merton', 'Middlesbrough', 'Milton Keynes', 'Newham', 'Norfolk', 'North East Lincolnshire', 'North Lincolnshire', 'North Somerset', 'North Yorkshire', 'Northamptonshire', 'Northumberland', 'Nottingham', 'Nottinghamshire', 'Oxfordshire', 'Peterborough', 'Plymouth', 'Poole', 'Portsmouth', 'Redbridge', 'Redcar and Cleveland', 'Richmond upon Thames', 'Rutland', 'Shropshire', 'Somerset', 'South Gloucestershire', 'South Yorkshire', 'Southampton', 'Southend-on-Sea', 'Southwark', 'Staffordshire', 'Stockton-on-Tees', 'Stoke-on-Trent', 'Suffolk', 'Surrey', 'Sutton', 'Swindon', 'Telford and Wrekin', 'Thurrock', 'Torbay', 'Tower Hamlets', 'Tyne and Wear', 'Waltham Forest', 'Wandsworth', 'Warrington', 'Warwickshire', 'West Midlands', 'West Sussex', 'West Yorkshire', 'Westminster', 'Wiltshire', 'Worcestershire', 'York', 'Antrim', 'Ards', 'Armagh', 'Ballymena', 'Ballymoney', 'Banbridge', 'Belfast', 'Carrickfergus', 'Castlereagh', 'Coleraine', 'Cookstown', 'Craigavon', 'Derry', 'Down', 'Dungannon', 'Fermanagh', 'Larne', 'Limavady', 'Lisburn', 'Magherafelt', 'Moyle', 'Newry and Mourne', 'Newtownabbey', 'North Down', 'Omagh', 'Strabane', 'Aberdeen', 'Aberdeenshire', 'Angus', 'Argyll and Bute', 'Clackmannanshire', 'Dumfries and Galloway', 'Dundee', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian', 'East Renfrewshire', 'Edinburgh', 'Eilean Siar', 'Falkirk', 'Fife', 'Glasgow', 'Highland', 'Inverclyde', 'Midlothian', 'Moray', 'North Ayshire', 'North Lanarkshire', 'Orkney Islands', 'Perthshire and Kinross', 'Renfrewshire', 'Scottish Borders', 'Shetland Islands', 'South Ayrshire', 'South Lanarkshire', 'Stirling', 'West Dunbartonshire', 'West Lothian', 'Anglesey', 'Blaenau Gwent', 'Bridgend', 'Caerphilly', 'Cardiff', 'Carmarthenshire', 'Ceredigion', 'Conwy', 'Denbighshire', 'Flintshire', 'Gwynedd', 'Merthyr Tydfil', 'Monmouthshire', 'Neath Port Talbot', 'Newport', 'Pembrokeshire', 'Powys', 'Rhondda, Cynon, Taff', 'Swansea', 'Torfaen', 'Vale of Glamorgan', 'Wrexham'])
#from counties_wgs84
UK_COUNTRIES = clean(['England', 'Northern Ireland', 'Scotland', 'Wales'])

EXCLUDE_FROM_GAZETTEERS = ['little ledge', 'little pool', 'little bay', 'higher ledge', 'flat rock', 'fennel', 'samson', 'shoals of mackerel', 'the green', 'nags head', 'day mark', 'the calf', 'rush hour', 'northward', 'take-off', 'cones', 'gull rock', 'bizzies', 'camel estuary', 'fowey estuary', 'river camel estuary', 'the harbour wall', 'the river fowey', 'avon estuary', 'boundary wall', 'dartmouth', 'dominos', 'exe estuary', 'river exe', 'river tavy', 'salcombe estuary', 'the castle', 'the exe estuary', 'the river avon', 'the river dart', 'the river otter', 'the river parrett', 'the taw estuary', 'the teign estuary', 'yealm estuary', 'coastguard lookout', 'dead tree', 'kite surfing', 'lest we forget', 'muddy waters', 'river waveney', 'stour estuary', 'the orwell estuary', 'the river deben', 'the river waveney', 'the river yare', 'kite surfing', 'chalk cliffs', 'coastguard lookout', 'picnic area', 'the river blackwater', 'the river medway', 'the river stour', 'river tees', 'the river humber', 'the river ouse', 'kent estuary', 'leven estuary', 'lune estuary', 'receding tide', 'the kent estuary', 'the river ribble', 'the river wyre', 'blyth estuary', 'the castle', 'river wey', 'river yar', 'chalk cliff', 'chalk cliffs', 'cuckmere river', 'job centre', 'river arun', 'river cuckmere', 'river rother', 'dartford']

EXCLUDED_GAZ_CLEANED_TXT = '_EXCLUDED_CLEAN_GAZ.PY_'