# ---------------------------------------------------------------------------
# tmp.py
# Created on: 2017-12-21 10:38:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
VenueCnt3x3PAMSansPAMClip1 = "C:\\Users\\Graham Monkman\\OneDrive\\Documents\\PHD\\My Papers\\WalesRSA-MSP\\GIS\\RSA-MSP-SCRATCH.gdb\\VenueCnt3x3PAMSansPAMClip1"
Input_raster_or_constant_value_2 = "1000"
deleteme = "C:\\Users\\Graham Monkman\\OneDrive\\Documents\\PHD\\My Papers\\WalesRSA-MSP\\GIS\\RSA-MSP-SCRATCH.gdb\\deleteme"

# Process: Times
arcpy.gp.Times_sa(VenueCnt3x3PAMSansPAMClip1, Input_raster_or_constant_value_2, deleteme)

